[profile.default]
evm_version = "prague"
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
wrap_comments = true

[rpc_endpoints]
baseSepolia = "https://sepolia.base.org"
sepolia = "https://sepolia.drpc.org"
inkSepolia = "https://rpc-gel-sepolia.inkonchain.com"
basecampTestnet = "https://rpc.basecamp.t.raas.gelato.cloud"
storyTestnet = "https://aeneid.storyrpc.io"
arbitrumSepolia = "https://arbitrum-sepolia.drpc.org"
flowTestnet = "https://testnet.evm.nodes.onflow.org"
alephZeroTestnet = "https://rpc.alephzero-testnet.gelato.digital"
arbBlueberry = "https://rpc.arb-blueberry.gelato.digital"
berachainTestnet = "https://bepolia.rpc.berachain.com"
blastSepolia = "https://168587773.rpc.thirdweb.com"
chiadoTestnet = "https://rpc.chiadochain.net"
liskSepolia = "https://rpc.sepolia-api.lisk.com"
monadTestnet = "https://testnet-rpc.monad.xyz"
optimismSepolia = "https://sepolia.optimism.io"
polygonAmoy = "https://rpc-amoy.polygon.technology"
reyaCronos = "https://rpc.reya-cronos.gelato.digital"
unichainSepolia = "https://sepolia.unichain.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[etherscan]
baseSepolia = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
arbitrumSepolia = { key = "${ETHERSCAN_API_KEY}" }
