[profile.default]
evm_version = "prague"
optimizer = true
optimizer_runs = 200

[fmt]
line_length = 100
wrap_comments = true

[rpc_endpoints]
basesepolia = "https://sepolia.base.org"
sepolia = "https://sepolia.drpc.org"
inksepolia = "https://rpc-gel-sepolia.inkonchain.com"
basecampTestnet = "https://rpc.basecamp.t.raas.gelato.cloud"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
